### ISSUE TITLE
Module not found: Can't resolve '@table-library/react-table-library/material-ui'

### ISSUE THREAD

**Issue by zehawki** [table-library/react-table-library#43]
When attempting to use the material-ui theme as given here: https://react-table-library.com/?path=/docs/library-themes-material-ui--base, 

`import { DEFAULT_OPTIONS, getTheme } from '@table-library/react-table-library/material-ui';`

I get:

`Module not found: Can't resolve '@table-library/react-table-library/material-ui'`

Further, under Storybook > Lib themes > Material UI > Editable (https://react-table-library.com/?path=/docs/library-themes-material-ui--editable), it has:

`import { DEFAULT_OPTIONS, getTheme } from '@table-library/react-table-library/themes/material';`

That doesnt work either, and 

`import { DEFAULT_OPTIONS, getTheme } from '@table-library/react-table-library/themes/material-ui';`

also doesnt work.

Am I missing something?

**Comment by rwieruch** [comment]
Can you try `import { DEFAULT_OPTIONS, getTheme } from '@table-library/react-table-library/material';`

Need to update the docs here, sorry!

**Comment by mrsolis93** [comment]
Thanks! Also had this issue.

**Comment by proddy** [comment]
me too! Then I discovered how powerful this library is when using custom themes like for example:

```css
 const entities_theme = useTheme({
    BaseRow: `
      font-size: 14px;
      color: white;
      height: 32px;
    `,
    HeaderRow: `
      text-transform: uppercase;
      background-color: black;
      border-bottom: 1px solid #e0e0e0;
      color: #90CAF9;
    `,
    Row: `
      background-color: #1e1e1e;
      border-top: 1px solid #565656;
      border-bottom: 1px solid #565656;
      position: relative;
      z-index: 1;
      &:not(:last-of-type) {
        margin-bottom: -1px;
      }
      &:not(:first-of-type) {
        margin-top: -1px;
      }
      &:hover {
        z-index: 2;
        color: white;
        border-top: 1px solid #177ac9;
        border-bottom: 1px solid #177ac9;
      },
      &.tr.tr-body.row-select.row-select-single-selected, &.tr.tr-body.row-select.row-select-selected {
        background-color: #3d4752;
        color: white;
        font-weight: normal;
        z-index: 2;
        border-top: 1px solid #177ac9;
        border-bottom: 1px solid #177ac9;
      }
    `,
    BaseCell: `
      border-top: 1px solid transparent;
      border-right: 1px solid transparent;
      border-bottom: 1px solid transparent;
      &:nth-of-type(1) {
        left: 0px;
        min-width: 124px;
        width: 124px;
      }
      &:nth-of-type(2) {
        min-width: 70%;
        width: 70%;
      }
    `,
    HeaderCell: `
    padding-left: 0px;
    &:nth-of-type(2) {
      border-right: 1px solid #565656;
    }
    `
  });
```

```html
      <Table
          data={{ nodes: ... }}
          theme={entities_theme}
          layout={{ custom: true, horizontalScroll: true }}
      >
```

@rwieruch is their a way I can donate without being a monthly Sponsor? I would buy your React book but I'm no noobie anymore
